config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#home'
  get '/users/new' => 'users#new'
  post '/users/create' => 'users#create'

  get '/sessions/new' => 'sessions#new'
  post '/sessions/create' => 'sessions#create'
  get 'sessions/destroy' => 'sessions#destroy'

  get '/user_details/new' => 'user_details#new'
  get '/user_details/details1' => 'user_details#details1'
  get '/user_details/details2' => 'user_details#details2'
  post '/user_details/create' => 'user_details#create'
  get '/user_details/show' => 'user_details#show'
  get '/user_details/move_to' => 'user_details#move_to'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one :user_detail
    validates :email, :password, presence: true
    validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ 
    validates :password, length: { minimum: 6 }
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
    belongs_to :user 
    validates_uniqueness_of :user_id
    validates :first_name, :last_name, :bank_account_no, presence: true
    validates :swift_no, :phone_no, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception 
 
    def current_user
         @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end 
    helper_method :current_user 
    def authenticate_user! 
     redirect_to '/login' unless current_user 
    end 
end
  
   
   

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
   def create
         user = User.find_by(email: params[:email])
         
         if (user && user.authenticate(params[:password]))
         session[:user_id] = user.id
         flash[:notice] = 'Successfully Logged In!'
         redirect_to '/user_details/move_to' 
         
         else
         flash[:notice] = 'Invalid Username or Password'
         render '/sessions/new'

         end
         
    
   end
    def destroy
     session[:user_id] = nil
     @current_user = nil
     flash.now[:notice] = 'Successfully Logged Out!'
     render '/sessions/new'
    end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
    before_action :require_login, only: [:show]
    
     def details1
       
        session[:first_name] = params[:first_name]
        session[:last_name] = params[:last_name]
        session[:phone_no] = params[:phone_no]
        
        render '/user_details/details2'
        
     end

    
    def create
        @user_details = UserDetail.new(
            first_name: session[:first_name],
            last_name: session[:last_name],
            phone_no: session[:phone_no],
            bank_account_no: params[:bank_account_no],
            ifsc: params[:ifsc],
            swift_no: params[:swift_no],
            user_id: session[:user_id]
        )
        if @user_details.save 
            session[:user_details_id] =  @user_details.id      
            flash[:notice] = "Succesfully created User!!"
            redirect_to '/user_details/show'
        else
            render '/user_details/details2' 
        end
        
    end

    def move_to
        
        if (current_user && current_user.user_detail.present?)
            redirect_to '/user_details/show' 
        else
            render '/user_details/details1'
        end
    end

    def show
        @userdetail = UserDetail.find(session[:user_details_id])
    end

    private
 
  def require_login
    unless current_user
      flash[:notice] = "You must be logged in to access this section"
      redirect_to 'sessions/new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    end
    def create
        @user = User.new(
            email: params[:email],
            password: params[:password],
            password_confirmation: params[:password_confirmation]
        )
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "Succesfully created User!!"
            render '/sessions/new'
        else
            render '/users/new'
        end
    end

    def home
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Signup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_details/details1.html.erb
<div class="container h-100" style="background-color:powderblue;">
<div class="row h-100 justify-content-center align-items-center">
<div class="col-10 col-md-8 col-lg-6">
<h2> Create Account- Form-1</h2>
<div class="alert alert-warning">
<%= notice%>
</div>

<%=form_tag '/user_details/details1', method: :get do%>
 
 <div class="form-group">
  
  <%= text_field_tag :first_name, nil, :required => true, :placeholder => 'first name' %>
 </div>
 <div class="form-group">
 
  <%= text_field_tag :last_name, nil, :required => true, :placeholder => 'last name'%>
 </div>
 <div class="form-group">
  
  <%= number_field_tag :phone_no, nil, :required => false, :placeholder => 'phone no'%>
 </div>
 
<%= submit_tag 'Next', class: "btn btn-primary"%>
<%end%>
</div>
</div>
</div>

app/views/user_details/details2.html.erb
<div class="container h-100" style="background-color:powderblue;">
<div class="row h-100 justify-content-center align-items-center">
<div class="col-10 col-md-8 col-lg-6">
<h2> Create Account Form-2</h2>
<% if(@user_details!= nil) %>
<% if @user_details.errors.any? %>
  <div class="alert alert-warning">
        <ul>
        <% @user_details.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
        </ul>
  </div>
<% end %>
<% end %>
<%=form_tag '/user_details/create', method: :post do%>
 
 <div class="form-group">
  
  <%= text_field_tag :bank_account_no, nil, :required => true, :placeholder => 'bank account no'%>
 </div>
 <div class="form-group">
  
  <%= text_field_tag :ifsc, nil, :required => false, :placeholder => 'ifsc'%>
 </div>
 <div class="form-group">
  
  <%= number_field_tag :swift_no, nil, :required => false, :placeholder => 'swift'%>
 </div>
 
<%= submit_tag 'Submit', class: "btn btn-primary"%>
<%end%>
</div>
</div>
</div>

app/views/user_details/show.html.erb
<div class="container h-100" style="background-color:powderblue;">
<div class="row h-100 justify-content-center align-items-center">
<div class="col-10 col-md-8 col-lg-6">
<h2> User Details</h2>
<div class="alert alert-warning">
<%= notice%>
</div>
 
 <div>
  <%= label_tag :first_name%>
  <%= @userdetail.first_name%>
  
 </div>
 <div>
  <%= label_tag :last_name%>
  <%= @userdetail.last_name%>
  
 </div>
 <div>
  <%= label_tag :phone_no%>
  <%= @userdetail.phone_no%>
  
 </div>
 <div>
 <%= label_tag :bank_account_no%>
  <%= @userdetail.bank_account_no%>
  
 </div>
 <div>
  <%= label_tag :ifsc%>
  <%= @userdetail.ifsc%>
  
 </div>
 <div>
  <%= label_tag :swift_no%>
  <%= @userdetail.swift_no%>
  
 </div>
 
 <%= link_to 'Logout', sessions_destroy_path %>
</div>
</div>
</div>

app/views/users/home.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>

<!-- As a link -->
<br><br><br><br>
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
<%= link_to "Already have an account? Login here",  sessions_new_path,  {:style=>'width:50%;', :class => "css_class"} %>
 
<%= link_to "Signup Here", users_new_path %>
   
</nav>

app/views/users/new.html.erb
<div class="container h-100" style="background-color:powderblue;">
<div class="row h-100 justify-content-center align-items-center">
<div class="col-10 col-md-8 col-lg-6">
<h2> Create Account</h2>
<% if(@user != nil) %>
<% if @user.errors.any? %>
  <div class="alert alert-warning">
  
    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% end %>
<%=form_tag '/users/create', method: :post do%>
 
 <div class="form-group">
  
  <%= text_field_tag :email, nil, :required => true, :placeholder => 'email'%>
 </div>
 <div class="form-group">
 
  <%= password_field_tag :password, nil, :required => true, :placeholder => 'password'%>
 </div>
 <div class="form-group">
 
  <%= password_field_tag :password_confirmation, nil, :required => true, :placeholder => 'password confirmation'%>
 </div>
 
<%= submit_tag 'Sign Up', class: "btn btn-primary"%>
<%end%>
</div>
</div>
</div>